job:
    script:
        - mkdir Debug-AT91EK
        - cd Debug-AT91EK
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - cmake --build . -j

        - mkdir Debug-iOBC
        - cd Debug-iOBC
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBOARD_IOBC=ON ..
        - cmake --build . -j

        - mkdir MinSizeRel-AT91EK
        - cd MinSizeRel-AT91EK
        - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
        - cmake --build . -j

        - mkdir MinSizeRel-iOBC
        - cd MinSizeRel-iOBC
        - cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DBOARD_IOBC=ON ..
        - cmake --build . -j
