#ifndef BOOTLOADER_IOBC_NORFLASH_BL_IOBC_NORFLASH_H_
#define BOOTLOADER_IOBC_NORFLASH_BL_IOBC_NORFLASH_H_

#include <stdbool.h>

extern bool fram_faulty;

#endif /* BOOTLOADER_IOBC_NORFLASH_BL_IOBC_NORFLASH_H_ */
