/** 
 * @brief	Auto-generated object translation file.
 * @details
 * Contains 21 translations.
 * Generated on: 2021-05-18 16:29:28
 */
#include "translateObjects.h"

const char *FSFW_OBJECTS_START_STRING = "FSFW_OBJECTS_START";
const char *PUS_SERVICE_1_VERIFICATION_STRING = "PUS_SERVICE_1_VERIFICATION";
const char *PUS_SERVICE_2_DEVICE_ACCESS_STRING = "PUS_SERVICE_2_DEVICE_ACCESS";
const char *PUS_SERVICE_3_HOUSEKEEPING_STRING = "PUS_SERVICE_3_HOUSEKEEPING";
const char *PUS_SERVICE_5_EVENT_REPORTING_STRING = "PUS_SERVICE_5_EVENT_REPORTING";
const char *PUS_SERVICE_8_FUNCTION_MGMT_STRING = "PUS_SERVICE_8_FUNCTION_MGMT";
const char *PUS_SERVICE_9_TIME_MGMT_STRING = "PUS_SERVICE_9_TIME_MGMT";
const char *PUS_SERVICE_17_TEST_STRING = "PUS_SERVICE_17_TEST";
const char *PUS_SERVICE_20_PARAMETERS_STRING = "PUS_SERVICE_20_PARAMETERS";
const char *PUS_SERVICE_200_MODE_MGMT_STRING = "PUS_SERVICE_200_MODE_MGMT";
const char *PUS_SERVICE_201_HEALTH_STRING = "PUS_SERVICE_201_HEALTH";
const char *HEALTH_TABLE_STRING = "HEALTH_TABLE";
const char *MODE_STORE_STRING = "MODE_STORE";
const char *EVENT_MANAGER_STRING = "EVENT_MANAGER";
const char *INTERNAL_ERROR_REPORTER_STRING = "INTERNAL_ERROR_REPORTER";
const char *TC_STORE_STRING = "TC_STORE";
const char *TM_STORE_STRING = "TM_STORE";
const char *IPC_STORE_STRING = "IPC_STORE";
const char *TIME_STAMPER_STRING = "TIME_STAMPER";
const char *FSFW_OBJECTS_END_STRING = "FSFW_OBJECTS_END";
const char *NO_OBJECT_STRING = "NO_OBJECT";

const char* translateObject(object_id_t object) {
	switch( (object & 0xFFFFFFFF) ) {
	case 0x53000000:
		return FSFW_OBJECTS_START_STRING;
	case 0x53000001:
		return PUS_SERVICE_1_VERIFICATION_STRING;
	case 0x53000002:
		return PUS_SERVICE_2_DEVICE_ACCESS_STRING;
	case 0x53000003:
		return PUS_SERVICE_3_HOUSEKEEPING_STRING;
	case 0x53000005:
		return PUS_SERVICE_5_EVENT_REPORTING_STRING;
	case 0x53000008:
		return PUS_SERVICE_8_FUNCTION_MGMT_STRING;
	case 0x53000009:
		return PUS_SERVICE_9_TIME_MGMT_STRING;
	case 0x53000017:
		return PUS_SERVICE_17_TEST_STRING;
	case 0x53000020:
		return PUS_SERVICE_20_PARAMETERS_STRING;
	case 0x53000200:
		return PUS_SERVICE_200_MODE_MGMT_STRING;
	case 0x53000201:
		return PUS_SERVICE_201_HEALTH_STRING;
	case 0x53010000:
		return HEALTH_TABLE_STRING;
	case 0x53010100:
		return MODE_STORE_STRING;
	case 0x53030000:
		return EVENT_MANAGER_STRING;
	case 0x53040000:
		return INTERNAL_ERROR_REPORTER_STRING;
	case 0x534f0100:
		return TC_STORE_STRING;
	case 0x534f0200:
		return TM_STORE_STRING;
	case 0x534f0300:
		return IPC_STORE_STRING;
	case 0x53500010:
		return TIME_STAMPER_STRING;
	case 0x53ffffff:
		return FSFW_OBJECTS_END_STRING;
	case 0xFFFFFFFF:
		return NO_OBJECT_STRING;
	default:
		return "UNKNOWN_OBJECT";
	}
	return 0;
}
