#ifndef CONFIG_RETURNVALUES_CLASSIDS_H_
#define CONFIG_RETURNVALUES_CLASSIDS_H_

#include <fsfw/returnvalues/FwClassIds.h>

/**
 * @brief   CLASS_ID defintions which are required for custom returnvalues.
 */
namespace CLASS_ID {
enum {
	MISSION_CLASS_ID_START = FW_CLASS_ID_COUNT,
	RS232_COM_IF, //RS232C
	RS232_POLLING, //RS232P
	RS485_POLLING,
	RS485_COM_IF, //RS485
	I2C_COM_IF, //I2C
	SPI_COM_IF, //SPIC
	GPS_HANDLER,
	PUS_SERVICE_3,
	PUS_PARSER, //PUSP
	SD_CARD_ACCESS,
	SD_CARD_HANDLER, //SDCH
	SW_IMAGE_HANDLER,
};
}


#endif /* CONFIG_RETURNVALUES_CLASSIDS_H_ */
